<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Whizz\User\Controller\UserController' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/UserController.php';
include_once \dirname(__DIR__, 4).'/src/Repository/UserRepository.php';

return $this->services['Whizz\\User\\Controller\\UserController'] = new \Whizz\User\Controller\UserController(new \Whizz\User\Repository\UserRepository());
