<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUPbllOh\srcWhizz_User_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUPbllOh/srcWhizz_User_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUPbllOh.legacy');

    return;
}

if (!\class_exists(srcWhizz_User_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUPbllOh\srcWhizz_User_KernelTestDebugContainer::class, srcWhizz_User_KernelTestDebugContainer::class, false);
}

return new \ContainerUPbllOh\srcWhizz_User_KernelTestDebugContainer([
    'container.build_hash' => 'UPbllOh',
    'container.build_id' => '1c98cf5a',
    'container.build_time' => 1625617345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUPbllOh');
