<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8csYzHj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8csYzHj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8csYzHj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8csYzHj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8csYzHj\App_KernelDevDebugContainer([
    'container.build_hash' => '8csYzHj',
    'container.build_id' => 'b9dc7192',
    'container.build_time' => 1625537390,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8csYzHj');
